gui:
  enlargedSideViewLocation: top
  theme:
    lightTheme: false
    selectedLineBgColor:
      - black
  showRandomTip: true
  showCommandLog: true
  nerdFontsVersion: 3
git:
  pagers:
    - colorArg: always
      pager: 'delta --dark --paging=never --diff-highlight'
    - colorArg: always
      pager: 'delta --dark --paging=never --diff-so-fancy'
    - colorArg: always
      pager: 'delta --dark --paging=never'
confirmOnQuit: false
quitOnTopLevelReturn: false
os:
  editPreset: 'nvim'
disableStartupPopups: true
notARepository: 'quit'
promptToReturnFromSubprocess: false
